
import React from "react";
import Layout from "@/components/layout/Layout";
import { FileText, AlertTriangle, Check } from "lucide-react";

const Terms = () => {
  return (
    <Layout>
      <div className="container px-4 py-8 mx-auto sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>

          <div className="prose max-w-none">
            <div className="flex items-center mb-4">
              <FileText className="w-6 h-6 mr-3 text-cleanscan-green" />
              <p className="text-lg font-medium">Last Updated: April 9, 2025</p>
            </div>
            
            <p className="mb-6">
              Welcome to CleanScan. These Terms of Service ("Terms") govern your use of the CleanScan web application and all related services. By using CleanScan, you agree to these Terms. If you disagree with any part of these Terms, you may not use our service.
            </p>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">1. Use of Service</h2>
              
              <p className="mb-4">
                CleanScan provides a tool for analyzing product ingredients using artificial intelligence. You may use this service for personal, non-commercial purposes, subject to these Terms.
              </p>
              
              <p>
                You agree not to misuse our services or help others to do so. Misuse includes but is not limited to:
              </p>
              
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Attempting to bypass or circumvent any security features of the service</li>
                <li>Using automated systems or software to extract data from the service</li>
                <li>Attempting to interfere with the proper functioning of the service</li>
                <li>Placing excessive load on our infrastructure</li>
              </ul>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">2. Disclaimer of Warranties</h2>
              
              <div className="bg-cleanscan-light-gray rounded-lg p-5 mb-4 flex items-start">
                <AlertTriangle className="w-6 h-6 mr-3 text-cleanscan-yellow shrink-0" />
                <p className="text-sm">
                  CleanScan is provided "as is," without warranty of any kind. We do not guarantee the accuracy, completeness, or usefulness of the information provided by our service. The ingredient analysis and categorizations are generated by artificial intelligence and should not be considered definitive or a substitute for professional advice.
                </p>
              </div>
              
              <p>
                You understand and agree that you use CleanScan at your own risk. We explicitly disclaim all warranties, whether express, implied, or statutory, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">3. Limitation of Liability</h2>
              
              <p className="mb-4">
                To the maximum extent permitted by applicable law, CleanScan, its affiliates, and their respective officers, directors, employees, agents, suppliers, and licensors shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
              </p>
              
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Your use or inability to use the service</li>
                <li>Any action taken based on the information provided by the service</li>
                <li>Unauthorized access to or alteration of your data</li>
                <li>Any other matter relating to the service</li>
              </ul>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">4. Content Ownership</h2>
              
              <p>
                CleanScan and its licensors own all intellectual property rights in the service, including but not limited to software, logos, and design elements. You may not copy, modify, distribute, sell, or lease any part of our service without our explicit permission.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">5. User Content</h2>
              
              <p className="mb-4">
                When you use CleanScan to scan or manually enter ingredient lists, you grant us a non-exclusive, worldwide, royalty-free license to use, store, and process that content for the purpose of providing and improving our service.
              </p>
              
              <p>
                You represent and warrant that you have all necessary rights to submit any content to CleanScan and that such content does not infringe on any third-party rights.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">6. Privacy</h2>
              
              <p>
                Our Privacy Policy, available at <a href="/privacy" className="text-cleanscan-green hover:underline">cleanscan.app/privacy</a>, describes how we handle your personal data and protect your privacy when you use our service. By using CleanScan, you agree to the collection and use of information in accordance with our Privacy Policy.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">7. Advertisements</h2>
              
              <p>
                CleanScan may display advertisements provided by third-party ad services. These advertisements are clearly identified and are subject to the privacy policies and terms of service of the respective ad providers.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">8. Modifications to the Service</h2>
              
              <p>
                We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice. We shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the service.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">9. Changes to Terms</h2>
              
              <p>
                We may revise these Terms at any time by updating this page. By continuing to use CleanScan after such changes, you agree to be bound by the updated Terms.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">10. Governing Law</h2>
              
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
              </p>
            </div>
            
            <div className="mb-8">
              <h2 className="text-xl font-semibold mb-4">11. Contact Us</h2>
              
              <p>
                If you have any questions about these Terms, please contact us at:
              </p>
              
              <div className="mt-4 p-4 bg-cleanscan-light-green rounded-md">
                <p className="font-medium">CleanScan</p>
                <p>terms@cleanscan.app</p>
              </div>
            </div>
            
            <div className="flex items-center p-4 bg-white border border-green-200 rounded-lg">
              <Check className="w-6 h-6 mr-3 text-cleanscan-green" />
              <p className="text-sm">
                By using CleanScan, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;
